### ISSUE TITLE
Route animation not working

### ISSUE THREAD

**Issue by JimmyLumi** [NoahSchiro/every-street#8]
Hello,

Thanks for this work we have a similar issue we try to work with (Routing inspection).

While everything seems to work the routing animation is always empty on our side.

We are using this osm file:
[map.zip](https://github.com/NoahSchiro/every-street/files/10989122/map.zip)

Thanks!

**Comment by NoahSchiro** [comment]
Hi,

Thank you for raising this issue. I just wanted to let you know that I have downloaded your map and tried it out on my computer and got the same results. 

The issue, I have noted, is that I hard-coded in the coordinates of my town in testing and failed to adjust this when I was ready to wrap up the project. I will fix this shortly.

Thanks again for the issue! This was a simple oversight on my part

**Comment by NoahSchiro** [comment]
Resolved. Pull down the latest version of master and try again. Please comment here if you run into any other issues. Additionally, I added a "speed" variable on line 116 of main.py. Since your town is a bit smaller, you might want the animation to run slower, so if you make this number larger it will go slower. Eventually, this will integrated into a (better) CLI

**Comment by JimmyLumi** [comment]
Thanks for the quick fix!
